name: 'Test API Xpress'
description: 'Run Postman collections and upload results using Python.'
inputs:
  collection:
    description: 'Path to the Postman collection JSON file.'
    required: true
  report-file:
    description: 'Path to save the report file.'
    required: true
    default: 'results/report.json'
runs:
  using: 'docker'
  image: 'Dockerfile'
